version: '2'

services:
  php:
    build: ./docker/php
    depends_on:
      - mysql
      - composer
    links:
      - mysql:mysql
    volumes:
      - "./config/php.ini:/usr/local/etc/php/php.ini"
      - "./app:/var/www/symfony"
  composer:
      image: composer/composer:php7
      command: install
      volumes:
      - "./app:/app"
  mysql:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
      - "./config/my.cnf:/usr/local/etc/mysql/my.cnf"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: symfony
    ports:
      - 3306:3306
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - "./config/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./app:/var/www/symfony"
    depends_on:
      - php
      - composer
    links:
      - php
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      depends_on:
       - mysql
      ports:
          - 8080:80
      links:
          - mysql
      environment:
          PMA_HOST: mysql